#!/usr/bin/env bash
# Usage: manage prepare
# Summary: Prepare environment
# Help: This command is used to prepare the environment including configs of the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

find ${_MANAGE_ROOT}/template -mindepth 1 -type d -print0 | while read -d $'\0' TEMPLATE
do
  RELATIVENAME=${TEMPLATE//${_MANAGE_ROOT}\/template\//}

  if [ ! -d "${_MANAGE_ROOT}/merge/${RELATIVENAME}" ]
  then
    mkdir "${_MANAGE_ROOT}/merge/${RELATIVENAME}"
  fi

  if [ ! -d "${_MANAGE_ROOT}/${RELATIVENAME}" ]
  then
    mkdir "${_MANAGE_ROOT}/${RELATIVENAME}"
  fi
done

find ${_MANAGE_ROOT}/template -mindepth 1 -type f -print0 | while read -d $'\0' TEMPLATE
do
  RELATIVENAME=${TEMPLATE//${_MANAGE_ROOT}\/template\//}

  if [ ! -e "${_MANAGE_ROOT}/merge/${RELATIVENAME}" ]
  then
    cp "${TEMPLATE}" "${_MANAGE_ROOT}/merge/${RELATIVENAME}"
  fi

  ln -sf "${_MANAGE_ROOT}/merge/${RELATIVENAME}" "${_MANAGE_ROOT}/${RELATIVENAME}"
done
