#!/usr/bin/env bash
# Usage: manage stop
# Summary: Stop the server
# Help: This command is used to really stop the server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  manage-mcrcon "stop"
else
  echo "Server is not running"
fi
