#!/usr/bin/env bash
# Usage: manage root
# Summary: Prepare root config files
# Help: This command is used to prepare the root config files of the minecraft server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if [ ! -d ${_MANAGE_ROOT}/merge/root ]
then
  mkdir -p ${_MANAGE_ROOT}/merge/root
fi

for TEMPLATE in $(find ${_MANAGE_ROOT}/template/root -mindepth 1 -type d)
do
  RELATIVENAME=${TEMPLATE//${_MANAGE_ROOT}\/template\/root\//}

  if [ ! -d ${_MANAGE_ROOT}/merge/root/${RELATIVENAME} ]
  then
    mkdir ${_MANAGE_ROOT}/merge/root/${RELATIVENAME}
  fi

  if [ ! -d ${_MANAGE_ROOT}/${RELATIVENAME} ]
  then
    mkdir ${_MANAGE_ROOT}/${RELATIVENAME}
  fi
done

for TEMPLATE in $(find ${_MANAGE_ROOT}/template/root -mindepth 1 -type f)
do
  RELATIVENAME=${TEMPLATE//${_MANAGE_ROOT}\/template\/root\//}

  if [ ! -e ${_MANAGE_ROOT}/merge/root/${RELATIVENAME} ]
  then
    cp ${TEMPLATE} ${_MANAGE_ROOT}/merge/root/${RELATIVENAME}
  fi

  ln -sf ${_MANAGE_ROOT}/merge/root/${RELATIVENAME} ${_MANAGE_ROOT}/${RELATIVENAME}
done
