#!/usr/bin/env bash
# Usage: manage config
# Summary: Update server config
# Help: This command is used to update the server.properties configuration of the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

sed -i \
  -e "s/motd=.*/motd=${SERVER_MOTD}/" \
  -e "s/rcon\.password=.*/motd=${SERVER_RCONPWD}/" \
  /minecraft/server.properties
