#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the minecraft server
# Help: This command is used to really start the minecraft server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if pgrep -f minecraft_server.${MINECRAFT_VERSION}.jar
then
  echo "Server is already running"
else
  manage-root && /usr/bin/env java -Xmx${MINECRAFT_MAXHEAP} -Xms${MINECRAFT_MINHEAP} -jar ${_MANAGE_ROOT}/minecraft_server.${MINECRAFT_VERSION}.jar ${MINECRAFT_OPTS}
fi
