#!/usr/bin/env bash
# Usage: manage mcrcon <command>
# Summary: Execute a remote command
# Help: This command is used to execute remote commands on the server console.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "${@}"
else
  echo "Server is not running"
  exit 1
fi
