FROM ghcr.io/dockhippie/temurin:8-amd64@sha256:54a80cbf8443101bd3ab1623d4cb2017db44e674082fbbb58e3b14ef932a5484 AS build

# renovate: datasource=github-releases depName=itzg/rcon-cli
ENV RCONCLI_VERSION=1.4.8

RUN curl -sSLo - "https://github.com/itzg/rcon-cli/releases/download/${RCONCLI_VERSION}/rcon-cli_${RCONCLI_VERSION}_linux_amd64.tar.gz" | tar -xvz -C /tmp

FROM ghcr.io/dockhippie/temurin:8-amd64@sha256:54a80cbf8443101bd3ab1623d4cb2017db44e674082fbbb58e3b14ef932a5484

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575

WORKDIR /var/lib/minecraft
CMD ["/usr/bin/container"]

ENV MINECRAFT_VERSION 1.16.2
ENV MINECRAFT_JAR minecraft_server.${MINECRAFT_VERSION}.jar
ENV MINECRAFT_URL https://launcher.mojang.com/v1/objects/c5f6fb23c3876461d46ec380421e42b289789530/server.jar

RUN curl --create-dirs -sLo /usr/share/minecraft/${MINECRAFT_JAR} ${MINECRAFT_URL}

RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 minecraft && \
  useradd -u 1000 -d /var/lib/minecraft -g minecraft -s /bin/bash -M minecraft && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/rcon-cli /usr/bin/rcon-cli
COPY ./overlay /
