#!/usr/bin/env bash
# Usage: manage save-on
# Summary: Enable the autosave feature
# Help: This command is used to enable the autosave feature of the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "save-on"
