#!/usr/bin/env bash
# Usage: manage whitelist-off
# Summary: Disable the whitelist
# Help: This command is used to disable the whitelist on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "whitelist off"
