#!/usr/bin/env bash
# Usage: manage weather-clear [duration]
# Summary: Set the weather to clear
# Help: This command is used to change the weather to clear on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

DURATION=${1:-60}

if [ -z $DURATION ]
then
  echo "Provide a duration"
  exit 1
fi

mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "weather clear ${DURATION}"
