#!/usr/bin/env bash
# Usage: manage whitelist-list
# Summary: Whitelist on the server
# Help: This command is used to list the whitelist of the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "whitelist list"
