#!/usr/bin/env bash
# Usage: manage weather-rain [duration]
# Summary: Set the weather to rain
# Help: This command is used to change the weather to rain on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

DURATION=${1:-60}

if [ -z $DURATION ]
then
  echo "Provide a duration"
  exit 1
fi

mcrcon -H 127.0.0.1 -p ${SERVER_RCONPWD} "weather rain ${DURATION}"
