FROM ghcr.io/dockhippie/temurin:21-arm64@sha256:5f92a4868439eb0811f4102bd7c0306e44ff75c958269f9a2dc4b2715028c16b AS build

# renovate: datasource=github-releases depName=itzg/rcon-cli
ENV RCONCLI_VERSION=1.4.8

RUN curl -sSLo - "https://github.com/itzg/rcon-cli/releases/download/${RCONCLI_VERSION}/rcon-cli_${RCONCLI_VERSION}_linux_arm64.tar.gz" | tar -xvz -C /tmp

FROM ghcr.io/dockhippie/temurin:21-arm64@sha256:5f92a4868439eb0811f4102bd7c0306e44ff75c958269f9a2dc4b2715028c16b

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575

WORKDIR /var/lib/minecraft
CMD ["/usr/bin/container"]

ENV MINECRAFT_VERSION=1.21.11
ENV MINECRAFT_JAR=minecraft_server.${MINECRAFT_VERSION}.jar
ENV MINECRAFT_URL=https://piston-data.mojang.com/v1/objects/64bb6d763bed0a9f1d632ec347938594144943ed/server.jar

RUN curl --create-dirs -sLo /usr/share/minecraft/${MINECRAFT_JAR} ${MINECRAFT_URL}

RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 minecraft && \
  useradd -u 1000 -d /var/lib/minecraft -g minecraft -s /bin/bash -M minecraft && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/rcon-cli /usr/bin/rcon-cli
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
