---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: v1.20.5

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - v1.20.5/*
      - .github/workflows/v1.20.5.yml
  pull_request:
    branches:
      - master
    paths:
      - v1.20.5/*
      - .github/workflows/v1.20.5.yml

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        variant:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64
          - arch: arm
            platform: linux/arm/v7

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/minecraft-vanilla
            quay.io/webhippie/minecraft-vanilla
            ghcr.io/dockhippie/minecraft-vanilla
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Hub login
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Ghcr login
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: v1.20.5/
          provenance: false
          file: v1.20.5/Dockerfile.${{ matrix.variant.arch }}
          platforms: ${{ matrix.variant.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-vanilla:1.20.5-${{ matrix.variant.arch }}
            quay.io/webhippie/minecraft-vanilla:1.20.5-${{ matrix.variant.arch }}
            ghcr.io/dockhippie/minecraft-vanilla:1.20.5-${{ matrix.variant.arch }}

  manifest:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    needs:
      - docker

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Hub manifest
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: webhippie/minecraft-vanilla:1.20.5-ARCH
          target: webhippie/minecraft-vanilla:1.20.5
          ignore_missing: true

      - name: Quay manifest
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: quay.io/webhippie/minecraft-vanilla:1.20.5-ARCH
          target: quay.io/webhippie/minecraft-vanilla:1.20.5
          ignore_missing: true

      - name: Ghcr manifest
        uses: actionhippie/manifest@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: ghcr.io/dockhippie/minecraft-vanilla:1.20.5-ARCH
          target: ghcr.io/dockhippie/minecraft-vanilla:1.20.5
          ignore_missing: true

...
