FROM ghcr.io/dockhippie/temurin:18-amd64@sha256:b18549102804671a68790ebcc00040ba7f8266da3e0d2fd8622678f43e1eb9ca AS build

# renovate: datasource=github-releases depName=itzg/rcon-cli
ENV RCONCLI_VERSION=1.4.8

RUN curl -sSLo - "https://github.com/itzg/rcon-cli/releases/download/${RCONCLI_VERSION}/rcon-cli_${RCONCLI_VERSION}_linux_amd64.tar.gz" | tar -xvz -C /tmp

FROM ghcr.io/dockhippie/temurin:18-amd64@sha256:b18549102804671a68790ebcc00040ba7f8266da3e0d2fd8622678f43e1eb9ca

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575

WORKDIR /var/lib/minecraft
CMD ["/usr/bin/container"]

ENV MINECRAFT_VERSION 1.20.2
ENV MINECRAFT_JAR minecraft_server.${MINECRAFT_VERSION}.jar
ENV MINECRAFT_URL https://launcher.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar

RUN curl --create-dirs -sLo /usr/share/minecraft/${MINECRAFT_JAR} ${MINECRAFT_URL}

RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 minecraft && \
  useradd -u 1000 -d /var/lib/minecraft -g minecraft -s /bin/bash -M minecraft && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/rcon-cli /usr/bin/rcon-cli
COPY ./overlay /
