FROM ghcr.io/dockhippie/temurin:8-arm64@sha256:fba3ddecc5b0fab6e2845570265de3fa3396143f18eaf5049df2589f2b48343d AS build

# renovate: datasource=github-releases depName=itzg/rcon-cli
ENV RCONCLI_VERSION=1.4.8

RUN curl -sSLo - "https://github.com/itzg/rcon-cli/releases/download/${RCONCLI_VERSION}/rcon-cli_${RCONCLI_VERSION}_linux_arm64.tar.gz" | tar -xvz -C /tmp

FROM ghcr.io/dockhippie/temurin:8-arm64@sha256:fba3ddecc5b0fab6e2845570265de3fa3396143f18eaf5049df2589f2b48343d

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575

WORKDIR /var/lib/minecraft
CMD ["/usr/bin/container"]

ENV MINECRAFT_VERSION 1.14.2
ENV MINECRAFT_JAR minecraft_server.${MINECRAFT_VERSION}.jar
ENV MINECRAFT_URL https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar

RUN curl --create-dirs -sLo /usr/share/minecraft/${MINECRAFT_JAR} ${MINECRAFT_URL}

RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 minecraft && \
  useradd -u 1000 -d /var/lib/minecraft -g minecraft -s /bin/bash -M minecraft && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /tmp/rcon-cli /usr/bin/rcon-cli
COPY ./overlay /
