FROM webhippie/adoptopenjdk:16-amd64@sha256:c897414fed61e161ac60a57465ffb92c007bcfa492faeeeb05038d1636687bb0 as build

# renovate: datasource=github-releases depName=itzg/rcon-cli
ENV RCONCLI_VERSION=1.4.8

RUN curl -sSLo - "https://github.com/itzg/rcon-cli/releases/download/${RCONCLI_VERSION}/rcon-cli_${RCONCLI_VERSION}_linux_amd64.tar.gz" | tar -xvz -C /tmp

FROM webhippie/adoptopenjdk:16-amd64@sha256:c897414fed61e161ac60a57465ffb92c007bcfa492faeeeb05038d1636687bb0

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575

WORKDIR /var/lib/minecraft
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/container"]

ENV MINECRAFT_VERSION 1.15.1
ENV MINECRAFT_JAR minecraft_server.${MINECRAFT_VERSION}.jar
ENV MINECRAFT_URL https://launcher.mojang.com/v1/objects/4d1826eebac84847c71a77f9349cc22afd0cf0a1/server.jar

RUN curl --create-dirs -sLo /usr/share/minecraft/${MINECRAFT_JAR} ${MINECRAFT_URL}

RUN apt-get update && \
  apt-get upgrade -y && \
  groupadd -g 1000 minecraft && \
  useradd -u 1000 -d /var/lib/minecraft -g minecraft -s /bin/bash -M minecraft && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/**

COPY --from=build /tmp/rcon-cli /usr/bin/rcon-cli
COPY ./overlay /
